SET linesize 120
SET pagesize 100
ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-YYYY';

cl scr
PROMPT 'List of orders by employee'
PROMPT
PROMPT

ACCEPT v_employee CHAR FORMAT 'A6' PROMPT 'Enter Employee Name: '

COLUMN EmployeeID FORMAT A11 HEADING "EMPLOYEE ID";
COLUMN EmployeeName FORMAT A50 HEADING "EMPLOYEE NAME";
COLUMN OrderID FORMAT A10 HEADING "ORDER ID";
COLUMN OrderDate FORMAT A11 HEADING "ORDER DATE";
COLUMN Total FORMAT 99999.99 HEADING "TOTAL (RM)";

TTITLE CENTER 'Orders in charge for ' _DATE SKIP 2
COMPUTE SUM OF Total ON EmployeeID
BREAK ON EmployeeID SKIP 2 ON OrderID

SELECT EmployeeID, EmployeeName, OrderID, OrderDate, Total
FROM OrderEmployee
WHERE UPPER(EmployeeName) LIKE UPPER('%&v_employee%')
ORDER BY EmployeeID;

CLEAR COLUMNS
CLEAR BREAKS
TTITLE OFF